# Lab 2: numpy

#### Practice Exercise 1

Create the following NumPy arrays: 
1. A 1-D array called zeros having 10 elements and all the elements are set to zero. 
2. A 1-D array called vowels having the elements ‘a’, ‘e’, ‘i’, ‘o’ and ‘u’. 
3. A 2-D array called ones having 2 rows and 5 columns and all the elements are set to 1 and dtype as int. 
4. Use nested Python lists to create a 2-D array called myarray1 having 3 rows and 3 columns and store the following data: 2.7,  0,  -2,  3.4,  10.6,  0,  -19 99.9 13 
5. A 2-D array called myarray2 using arange() having 3 rows and 5 columns with start value = 4, step size 4 and dtype as float

In [2]:
# Write your answer here

import numpy as np

# 1-D array of zeros with 10 elements
zeros = np.zeros(10)

# 1-D array of vowels
vowels = np.array(['a', 'e', 'i', 'o', 'u'])

# 2-D array of ones with 2 rows and 5 columns (dtype=int)
ones = np.ones((2, 5), dtype=int)

# 2-D array using nested lists
myarray1 = np.array([[2.7, 0, -2], [3.4, 10.6, 0], [-19, 99.9, 13]])

# 2-D array using arange with start=4, step=4, dtype=float
myarray2 = np.arange(4, 64, 4, dtype=float).reshape(3, 5)

# Output to check the arrays
print("zeros:\n", zeros)
print("\nvowels:\n", vowels)
print("\nones:\n", ones)
print("\nmyarray1:\n", myarray1)
print("\nmyarray2:\n", myarray2)

zeros:
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

vowels:
 ['a' 'e' 'i' 'o' 'u']

ones:
 [[1 1 1 1 1]
 [1 1 1 1 1]]

myarray1:
 [[  2.7   0.   -2. ]
 [  3.4  10.6   0. ]
 [-19.   99.9  13. ]]

myarray2:
 [[ 4.  8. 12. 16. 20.]
 [24. 28. 32. 36. 40.]
 [44. 48. 52. 56. 60.]]

Using the arrays created in Question above, write NumPy commands for the following: 
1. Find the dimensions, shape, size, data type of the items and itemsize of arrays zeros, vowels, ones, myarray1 and myarray2. 
2. Reshape the array ones to have all the 10 elements in a single row. 
3. Display the 2nd and 3rd element of the array vowels. 
4. Display all elements in the 2nd and 3rd row of the array myarray1. 
5. Display the elements in the 1st and 2nd column of the array myarray1. 
6. Display the elements in the 1st column of the 2nd and 3rd row of the array myarray1. 
7. Reverse the array of vowels.

In [4]:
#Write your answer here

import numpy as np

# Arrays from the previous question
zeros = np.zeros(10)
vowels = np.array(['a', 'e', 'i', 'o', 'u'])
ones = np.ones((2, 5), dtype=int)
myarray1 = np.array([[2.7, 0, -2], [3.4, 10.6, 0], [-19, 99.9, 13]])
myarray2 = np.arange(4, 64, 4, dtype=float).reshape(3, 5)

# 1. Find dimensions, shape, size, data type, and item size
arrays = [zeros, vowels, ones, myarray1, myarray2]
for array in arrays:
    print(f"Array:\n{array}")
    print(f"Dimensions (ndim): {array.ndim}")
    print(f"Shape: {array.shape}")
    print(f"Size: {array.size}")
    print(f"Data type (dtype): {array.dtype}")
    print(f"Item size: {array.itemsize} bytes\n")

# 2. Reshape the array 'ones' to have all 10 elements in a single row
ones_reshaped = ones.reshape(1, 10)
print("Reshaped array 'ones':\n", ones_reshaped)

# 3. Display the 2nd and 3rd element of the array 'vowels'
print("\n2nd and 3rd elements of 'vowels':", vowels[1:3])

# 4. Display all elements in the 2nd and 3rd row of the array 'myarray1'
print("\nElements in the 2nd and 3rd row of 'myarray1':\n", myarray1[1:3, :])

# 5. Display the elements in the 1st and 2nd column of the array 'myarray1'
print("\nElements in the 1st and 2nd column of 'myarray1':\n", myarray1[:, 0:2])

# 6. Display the elements in the 1st column of the 2nd and 3rd row of 'myarray1'
print("\n1st column of 2nd and 3rd row of 'myarray1':\n", myarray1[1:3, 0])

# 7. Reverse the array 'vowels'
vowels_reversed = vowels[::-1]
print("\nReversed 'vowels':", vowels_reversed)

Array:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Dimensions (ndim): 1
Shape: (10,)
Size: 10
Data type (dtype): float64
Item size: 8 bytes

Array:
['a' 'e' 'i' 'o' 'u']
Dimensions (ndim): 1
Shape: (5,)
Size: 5
Data type (dtype): <U1
Item size: 4 bytes

Array:
[[1 1 1 1 1]
 [1 1 1 1 1]]
Dimensions (ndim): 2
Shape: (2, 5)
Size: 10
Data type (dtype): int64
Item size: 8 bytes

Array:
[[  2.7   0.   -2. ]
 [  3.4  10.6   0. ]
 [-19.   99.9  13. ]]
Dimensions (ndim): 2
Shape: (3, 3)
Size: 9
Data type (dtype): float64
Item size: 8 bytes

Array:
[[ 4.  8. 12. 16. 20.]
 [24. 28. 32. 36. 40.]
 [44. 48. 52. 56. 60.]]
Dimensions (ndim): 2
Shape: (3, 5)
Size: 15
Data type (dtype): float64
Item size: 8 bytes

Reshaped array 'ones':
 [[1 1 1 1 1 1 1 1 1 1]]

2nd and 3rd elements of 'vowels': ['e' 'i']

Elements in the 2nd and 3rd row of 'myarray1':
 [[  3.4  10.6   0. ]
 [-19.   99.9  13. ]]

Elements in the 1st and 2nd column of 'myarray1':
 [[  2.7   0. ]
 [  3.4  10.6]
 [-19.   99.9]]

1st column of 2nd and 3rd row of 'myarray1':
 [  3.4 -19. ]

Reversed 'vowels': ['u' 'o' 'i' 'e' 'a']

Using the arrays created in Question above, write NumPy commands for the following:
1. Divide all elements of array ones by 3. 
2. Add the arrays myarray1 and myarray2. 
3. Subtract myarray1 from myarray2 and store the result in a new array. 
4. Multiply myarray1 and myarray2 elementwise. 
5. Do the matrix multiplication of myarray1 and myarray2 and store the result in a new array myarray3. 
6. Divide myarray1 by myarray2. 
7. Find the cube of all elements of myarray1 and divide the resulting array by 2. 
8. Find the square root of all elements of myarray2   and divide the resulting array by 2. The result  should be rounded to two places of decimals.

In [12]:
import numpy as np

# Trim myarray2 to match the shape of myarray1 (trim columns)
myarray2_trimmed = myarray2[:, :3]

# 1. Add the arrays
added_arrays = myarray1 + myarray2_trimmed
print("\nSum of 'myarray1' and trimmed 'myarray2':\n", added_arrays)

# 2. Subtract myarray1 from myarray2_trimmed
subtracted_arrays = myarray2_trimmed - myarray1
print("\nDifference between trimmed 'myarray2' and 'myarray1':\n", subtracted_arrays)

# 3. Multiply myarray1 and myarray2_trimmed elementwise
elementwise_multiplication = myarray1 * myarray2_trimmed
print("\nElementwise multiplication of 'myarray1' and trimmed 'myarray2':\n", elementwise_multiplication)

# 4. Matrix multiplication of myarray1 and myarray2_trimmed
try:
    myarray3 = np.dot(myarray1, myarray2_trimmed.T)
    print("\nMatrix multiplication of 'myarray1' and 'trimmed myarray2' (myarray3):\n", myarray3)
except ValueError:
    print("\nMatrix multiplication is not possible due to shape mismatch.")

# 5. Divide myarray1 by myarray2_trimmed
division_result = np.divide(myarray1, myarray2_trimmed)
print("\nDivision of 'myarray1' by 'myarray2_trimmed':\n", division_result)

# 6. Cube of all elements of myarray1 and divide by 2
cubed_array = (myarray1 ** 3) / 2
print("\nCube of 'myarray1' divided by 2:\n", cubed_array)

# 7. Square root of all elements of myarray2_trimmed, divide by 2, and round to 2 decimal places
sqrt_array = np.sqrt(myarray2_trimmed) / 2
sqrt_array_rounded = np.round(sqrt_array, 2)
print("\nSquare root of 'myarray2_trimmed' divided by 2 (rounded to 2 decimals):\n", sqrt_array_rounded)

Sum of 'myarray1' and trimmed 'myarray2':
 [[  6.7   8.   10. ]
 [ 27.4  38.6  32. ]
 [ 25.  147.9  65. ]]

Difference between trimmed 'myarray2' and 'myarray1':
 [[  1.3   8.   14. ]
 [ 20.6  17.4  32. ]
 [ 63.  -51.9  39. ]]

Elementwise multiplication of 'myarray1' and trimmed 'myarray2':
 [[  10.8    0.   -24. ]
 [  81.6  296.8    0. ]
 [-836.  4795.2  676. ]]

Matrix multiplication of 'myarray1' and 'trimmed myarray2' (myarray3):
 [[-1.3200e+01  8.0000e-01  1.4800e+01]
 [ 9.8400e+01  3.7840e+02  6.5840e+02]
 [ 8.7920e+02  2.7572e+03  4.6352e+03]]

Division of 'myarray1' by 'myarray2_trimmed':
 [[ 0.675       0.         -0.16666667]
 [ 0.14166667  0.37857143  0.        ]
 [-0.43181818  2.08125     0.25      ]]

Cube of 'myarray1' divided by 2:
 [[ 9.841500e+00  0.000000e+00 -4.000000e+00]
 [ 1.965200e+01  5.955080e+02  0.000000e+00]
 [-3.429500e+03  4.985015e+05  1.098500e+03]]

Square root of 'myarray2_trimmed' divided by 2 (rounded to 2 decimals):
 [[1.   1.41 1.73]
 [2.45 2.65 2.83]
 [3.32 3.46 3.61]]

Using the arrays created above, write NumPy commands for the following: 
1. Find the transpose of ones and myarray2. 
2. Sort the array vowels in reverse. 
3. Sort the array myarray1 such that it brings the lowest value of the column in the first row and so on.

In [14]:
# Write your answer here
import numpy as np

# 1. Find the transpose of 'ones' and 'myarray2'
ones_transposed = ones.T
myarray2_transposed = myarray2.T

print("Transpose of 'ones':\n", ones_transposed)
print("\nTranspose of 'myarray2':\n", myarray2_transposed)

# 2. Sort the array 'vowels' in reverse order
vowels_sorted_reverse = np.sort(vowels)[::-1]
print("\n'vowels' sorted in reverse order:\n", vowels_sorted_reverse)

# 3. Sort 'myarray1' so that the lowest value of the column is in the first row, and so on
myarray1_sorted = np.sort(myarray1, axis=0)
print("\n'myarray1' sorted by columns (lowest value in first row):\n", myarray1_sorted)

Transpose of 'ones':
 [[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]

Transpose of 'myarray2':
 [[ 4. 24. 44.]
 [ 8. 28. 48.]
 [12. 32. 52.]
 [16. 36. 56.]
 [20. 40. 60.]]

'vowels' sorted in reverse order:
 ['u' 'o' 'i' 'e' 'a']

'myarray1' sorted by columns (lowest value in first row):
 [[-19.    0.   -2. ]
 [  2.7  10.6   0. ]
 [  3.4  99.9  13. ]]

Create a 2-D array called myarray4 using arange() having 14 rows and 3 columns with start value = -1, step size 0.25 having. Split this array row wise into 3 equal parts and print the result.

In [16]:
# Write your answer here

import numpy as np

# Create a 2-D array myarray4 with 14 rows and 3 columns using arange
start_value = -1
step_size = 0.25
total_elements = 14 * 3  # 14 rows * 3 columns = 42 elements

# Creating the array
myarray4 = np.arange(start_value, start_value + step_size * total_elements, step_size).reshape(14, 3)

print("Original myarray4:\n", myarray4)

# Split the array row-wise into 3 equal parts
split_arrays = np.array_split(myarray4, 3)

# Print the result of the split
print("\nSplitted arrays:")
for idx, arr in enumerate(split_arrays):
    print(f"\nPart {idx + 1}:\n", arr)

Original myarray4:
 [[-1.   -0.75 -0.5 ]
 [-0.25  0.    0.25]
 [ 0.5   0.75  1.  ]
 [ 1.25  1.5   1.75]
 [ 2.    2.25  2.5 ]
 [ 2.75  3.    3.25]
 [ 3.5   3.75  4.  ]
 [ 4.25  4.5   4.75]
 [ 5.    5.25  5.5 ]
 [ 5.75  6.    6.25]
 [ 6.5   6.75  7.  ]
 [ 7.25  7.5   7.75]
 [ 8.    8.25  8.5 ]
 [ 8.75  9.    9.25]]

Splitted arrays:

Part 1:
 [[-1.   -0.75 -0.5 ]
 [-0.25  0.    0.25]
 [ 0.5   0.75  1.  ]
 [ 1.25  1.5   1.75]
 [ 2.    2.25  2.5 ]]

Part 2:
 [[2.75 3.   3.25]
 [3.5  3.75 4.  ]
 [4.25 4.5  4.75]
 [5.   5.25 5.5 ]
 [5.75 6.   6.25]]

Part 3:
 [[6.5  6.75 7.  ]
 [7.25 7.5  7.75]
 [8.   8.25 8.5 ]
 [8.75 9.   9.25]]

Using the myarray4 created in the above questions, write commands for the following: 
1. Find the sum of all elements. 
2. Find the sum of all elements row wise
3. Find the sum of all elements column wise. 
4. Find the max of all elements. 
5. Find the min of all elements in each row. 
6. Find the mean of all elements in each row. 
7. Find the standard deviation column wise.

In [18]:
# Write your ansewr here

import numpy as np

# Calculating required statistics
total_sum = np.sum(myarray4)
row_wise_sum = np.sum(myarray4, axis=1)
column_wise_sum = np.sum(myarray4, axis=0)
max_value = np.max(myarray4)
row_wise_min = np.min(myarray4, axis=1)
row_wise_mean = np.mean(myarray4, axis=1)
column_wise_std = np.std(myarray4, axis=0)

# Printing results
print("Total sum of all elements:", total_sum)
print("Sum of all elements row-wise:", row_wise_sum)
print("Sum of all elements column-wise:", column_wise_sum)
print("Max of all elements:", max_value)
print("Min of all elements in each row:", row_wise_min)
print("Mean of all elements in each row:", row_wise_mean)
print("Standard deviation column-wise:", column_wise_std)

Total sum of all elements: 173.25
Sum of all elements row-wise: [-2.25  0.    2.25  4.5   6.75  9.   11.25 13.5  15.75 18.   20.25 22.5
 24.75 27.  ]
Sum of all elements column-wise: [54.25 57.75 61.25]
Max of all elements: 9.25
Min of all elements in each row: [-1.   -0.25  0.5   1.25  2.    2.75  3.5   4.25  5.    5.75  6.5   7.25
  8.    8.75]
Mean of all elements in each row: [-0.75  0.    0.75  1.5   2.25  3.    3.75  4.5   5.25  6.    6.75  7.5
  8.25  9.  ]
Standard deviation column-wise: [3.02334666 3.02334666 3.02334666]

#### Practice Exercise 2
Read the coordinates of the capital cities of the world from the country-capital-lat-long-population.csv file. Use NumPy to print the name and coordinates of the capital city closest to the Saudi Arabia capital - Riyadh.

Note that:

1. The Country Name for Saudi Arabia is given as Saudi Arabia in the data.
2. The ‘closeness’ of capital cities from the Saudi Arabia capital is based on the Euclidean distance of their coordinates to those of the Saudi Arabia capital.


Hints:

1. Use read_html() from the Pandas library to read the table.
2. Use the to_numpy() function of the Pandas DataFrame class to convert a DataFrame to a Numpy array
3. Use broadcasting to compute the euclidean distance of capital cities from Riyadh.

In [41]:
import pandas as pd
import numpy as np

# Step 1: Read the CSV file
file_path = 'country-capital-lat-long-population.csv'  # Replace with your actual file path
data = pd.read_csv(file_path)

# Step 2: Check the column names and the first few rows
print("Columns in the DataFrame:", data.columns.tolist())
print(data.head())

# Step 3: Convert Latitude and Longitude to numeric, forcing errors to NaN
data['Latitude'] = pd.to_numeric(data['Latitude'], errors='coerce')
data['Longitude'] = pd.to_numeric(data['Longitude'], errors='coerce')

# Step 4: Extract coordinates of Riyadh
riyadh_row = data[data['Country'] == 'Saudi Arabia']  # Use the correct column name
riyadh_coords = riyadh_row[['Latitude', 'Longitude']].to_numpy().flatten()  # Get Riyadh's coordinates

# Check for NaN values in Riyadh's coordinates
print(f"Riyadh Coordinates: {riyadh_coords}")
if np.any(np.isnan(riyadh_coords)):
    print("Riyadh coordinates contain NaN values. Check the data.")
else:
    # Step 5: Extract coordinates of all capital cities
    capitals_coords = data[['Capital City', 'Latitude', 'Longitude']].to_numpy()
    print(f"Capitals Coordinates:\n{capitals_coords}")

    # Ensure all coordinates are valid and numeric
    print("Data Types:", capitals_coords.dtype)
    print("Riyadh Latitude:", type(riyadh_coords[0]), "Longitude:", type(riyadh_coords[1]))

    # Step 6: Calculate Euclidean distances
    distances = np.sqrt((capitals_coords[:, 1] - riyadh_coords[0]) ** 2 + 
                        (capitals_coords[:, 2] - riyadh_coords[1]) ** 2)
    print("Distances:", distances)

    # Step 7: Find the index of the closest capital city
    closest_index = np.argmin(distances)

    # Step 8: Print the name and coordinates of the closest capital city
    closest_capital = capitals_coords[closest_index]
    print(f"Closest capital city to Riyadh:")
    print(f"Name: {closest_capital[0]}")
    print(f"Coordinates: Latitude = {closest_capital[1]}, Longitude = {closest_capital[2]}")

Columns in the DataFrame: ['Country', 'Capital City', 'Latitude', 'Longitude', 'Population', 'Capital Type']
          Country           Capital City  Latitude  Longitude  Population  \
0     Afghanistan                  Kabul   34.5289    69.1725     4011770
1         Albania        Tiranë (Tirana)   41.3275    19.8189      475577
2         Algeria  El Djazaïr  (Algiers)   36.7525     3.0420     2693542
3  American Samoa              Pago Pago  -14.2781  -170.7025       48526
4         Andorra       Andorra la Vella   42.5078     1.5211       22614

  Capital Type
0      Capital
1      Capital
2      Capital
3      Capital
4      Capital
Riyadh Coordinates: [24.6905 46.7096]
Capitals Coordinates:
[['Kabul' 34.5289 69.1725]
 ['Tiranë (Tirana)' 41.3275 19.8189]
 ['El Djazaïr  (Algiers)' 36.7525 3.042]
 ['Pago Pago' -14.2781 -170.7025]
 ['Andorra la Vella' 42.5078 1.5211]
 ['Luanda' -8.8368 13.2343]
 ['The Valley' 18.217 -63.0578]
 ["St. John's" 17.1172 -61.8457]
 ['Buenos Aires' -34.6051 -58.4004]
 ['Yerevan' 40.182 44.5146]
 ['Oranjestad' 12.524 -70.027]
 ['Canberra' -35.2835 149.1281]
 ['Wien (Vienna)' 48.2064 16.3707]
 ['Baku' 40.3777 49.892]
 ['Nassau' 25.0582 -77.3431]
 ['Al-Manamah (Manama)' 26.2154 50.5832]
 ['Dhaka' 23.7104 90.4074]
 ['Bridgetown' 13.1 -59.6167]
 ['Minsk' 53.9 27.5667]
 ['Bruxelles-Brussel' 50.8467 4.3499]
 ['Belmopan' 17.25 -88.7667]
 ['Cotonou' 6.3654 2.4183]
 ['Hamilton' 32.2915 -64.778]
 ['Thimphu' 27.4661 89.6419]
 ['La Paz' -16.5 -68.15]
 ['Sarajevo' 43.8486 18.3564]
 ['Gaborone' -24.6545 25.9086]
 ['Brasília' -15.7797 -47.9297]
 ['Road Town' 18.4167 -64.6167]
 ['Bandar Seri Begawan' 4.9403 114.9481]
 ['Sofia' 42.6975 23.3242]
 ['Ouagadougou' 12.3642 -1.5383]
 ['Bujumbura' -3.3822 29.3644]
 ['Praia' 14.9215 -23.5087]
 ['Phnum Pénh (Phnom Penh)' 11.5625 104.916]
 ['Yaoundé' 3.8667 11.5167]
 ['Ottawa-Gatineau' 45.4166 -75.698]
 ['Kralendijk' 12.15 -68.2667]
 ['George Town' 19.2866 -81.3744]
 ['Bangui' 4.3612 18.555]
 ["N'Djaména" 12.1067 15.0444]
 ['St. Helier' 49.188 -2.1049]
 ['St. Peter Port' 49.4598 -2.5353]
 ['Santiago' -33.4569 -70.6483]
 ['Beijing' 39.9075 116.3972]
 ['Hong Kong' 22.2796 114.1887]
 ['Macao' 22.2006 113.5461]
 ['Taibei' 25.047 121.5457]
 ['Bogotá' 4.6097 -74.0818]
 ['Moroni' -11.7022 43.2551]
 ['Brazzaville' -4.2658 15.2832]
 ['Rarotonga' -21.23 -159.76]
 ['San José' 9.9278 -84.0807]
 ['Abidjan' 5.3453 -4.0268]
 ['Zagreb' 45.8144 15.978]
 ['La Habana (Havana)' 23.1195 -82.3785]
 ['Willemstad' 12.1084 -68.9335]
 ['Lefkosia (Nicosia)' 35.1595 33.3669]
 ['Praha (Prague)' 50.088 14.4208]
 ["P'yongyang" 39.0339 125.7543]
 ['Kinshasa' -4.3276 15.3136]
 ['København (Copenhagen)' 55.6759 12.5655]
 ['Djibouti' 11.5877 43.1447]
 ['Roseau' 15.3017 -61.3881]
 ['Santo Domingo' 18.4896 -69.9018]
 ['Quito' -0.2299 -78.525]
 ['Al-Qahirah (Cairo)' 30.0392 31.2394]
 ['San Salvador' 13.6894 -89.1872]
 ['Malabo' 3.75 8.7833]
 ['Asmara' 15.3333 38.9333]
 ['Tallinn' 59.437 24.7535]
 ['Addis Ababa' 9.025 38.7469]
 ['Tórshavn' 62.0097 -6.7716]
 ['Stanley' -51.7012 -57.8494]
 ['Suva' -18.1416 178.4415]
 ['Helsinki' 60.1692 24.9402]
 ['Paris' 48.8534 2.3488]
 ['Cayenne' 4.9333 -52.3333]
 ['Papeete' -17.5333 -149.5667]
 ['Libreville' 0.3925 9.4537]
 ['Banjul' 13.4531 -16.6794]
 ['Tbilisi' 41.6941 44.8337]
 ['Berlin' 52.5244 13.4105]
 ['Accra' 5.556 -0.1969]
 ['Gibraltar' 36.1447 -5.3526]
 ['Athínai (Athens)' 37.9534 23.749]
 ['Nuuk (Godthåb)' 64.1835 -51.7216]
 ["St.George's" 12.0564 -61.7485]
 ['Basse-Terre' 15.9985 -61.7255]
 ['Hagåtña' 13.4757 144.7489]
 ['Ciudad de Guatemala (Guatemala City)' 14.6127 -90.5307]
 ['Conakry' 9.5716 -13.6476]
 ['Bissau' 11.8636 -15.5977]
 ['Georgetown' 6.8045 -58.1553]
 ['Port-au-Prince' 18.5392 -72.335]
 ['Vatican City' 41.9024 12.4533]
 ['Tegucigalpa' 14.0818 -87.2068]
 ['Budapest' 47.498 19.0399]
 ['Reykjavík' 64.1355 -21.8954]
 ['Delhi' 28.6667 77.2167]
 ['Jakarta' -6.2118 106.8416]
 ['Tehran' 35.6944 51.4215]
 ['Baghdad' 33.3406 44.4009]
 ['Dublin' 53.3331 -6.2489]
 ['Douglas' 54.15 -4.4833]
 ['Jerusalem' 31.769 35.2163]
 ['Roma (Rome)' 41.8947 12.4811]
 ['Kingston' 17.997 -76.7936]
 ['Tokyo' 35.6895 139.6917]
 ['Amman' 31.9552 35.945]
 ['Astana' 51.1801 71.446]
 ['Nairobi' -1.2833 36.8167]
 ['Tarawa' 1.3272 172.9813]
 ['Al Kuwayt (Kuwait City)' 29.3697 47.9783]
 ['Bishkek' 42.87 74.59]
 ['Vientiane' 17.9667 102.6]
 ['Riga' 56.946 24.1059]
 ['Bayrut (Beirut)' 33.9 35.4833]
 ['Maseru' -29.3167 27.4833]
 ['Monrovia' 6.3005 -10.7969]
 ['Tarabulus (Tripoli)' 32.8752 13.1875]
 ['Vaduz' 47.1415 9.5215]
 ['Vilnius' 54.6892 25.2798]
 ['Luxembourg' 49.6117 6.13]
 ['Antananarivo' -18.9137 47.5361]
 ['Lilongwe' -13.9669 33.7873]
 ['Kuala Lumpur' 3.1412 101.6865]
 ['Male' 4.1748 73.5089]
 ['Bamako' 12.65 -8.0]
 ['Valletta' 35.8997 14.5147]
 ['Majuro' 7.0897 171.3803]
 ['Fort-de-France' 14.6089 -61.0733]
 ['Nouakchott' 18.0858 -15.9785]
 ['Port Louis' -20.1619 57.4989]
 ['Mamoudzou' -12.7794 45.2272]
 ['Ciudad de México (Mexico City)' 19.4273 -99.1419]
 ['Palikir' 6.9174 158.1588]
 ['Monaco' 43.7333 7.4167]
 ['Ulaanbaatar' 47.9077 106.8832]
 ['Podgorica' 42.4411 19.2636]
 ['Brades Estate' 16.7918 -62.2106]
 ['Rabat' 34.0133 -6.8326]
 ['Maputo' -25.9653 32.5892]
 ['Nay Pyi Taw' 19.745 96.1297]
 ['Windhoek' -22.5594 17.0832]
 ['Nauru' -0.5308 166.9112]
 ['Kathmandu' 27.7017 85.3206]
 ['Amsterdam' 52.374 4.8897]
 ['Nouméa' -22.2763 166.4572]
 ['Wellington' -41.2866 174.7756]
 ['Managua' 12.1328 -86.2504]
 ['Niamey' 13.5137 2.1098]
 ['Abuja' 9.0574 7.4898]
 ['Alofi' -19.0585 -169.9213]
 ['Saipan' 15.2123 145.7545]
 ['Oslo' 59.9127 10.7461]
 ['Masqat (Muscat)' 23.6139 58.5922]
 ['Islamabad' 33.7035 73.0594]
 ['Koror' 7.3426 134.4789]
 ['Ciudad de Panamá (Panama City)' 8.9958 -79.5196]
 ['Port Moresby' -9.4431 147.1797]
 ['Asunción' -25.3007 -57.6359]
 ['Lima' -12.0432 -77.0282]
 ['Manila' 14.6042 120.9822]
 ['Warszawa (Warsaw)' 52.2298 21.0118]
 ['Lisboa (Lisbon)' 38.7169 -9.1399]
 ['San Juan' 18.4663 -66.1057]
 ['Ad-Dawhah (Doha)' 25.2747 51.5245]
 ['Seoul' 37.5683 126.9778]
 ['Chişinău' 47.0056 28.8575]
 ['Saint-Denis' -20.8823 55.4504]
 ['Bucuresti (Bucharest)' 44.4328 26.1043]
 ['Moskva (Moscow)' 55.755 37.6218]
 ['Kigali' -1.9474 30.0579]
 ['Jamestown' -15.9387 -5.7168]
 ['Basseterre' 17.2948 -62.7261]
 ['Castries' 14.006 -60.991]
 ['Saint-Pierre' 46.7738 -56.1815]
 ['Kingstown' 13.1587 -61.2248]
 ['Apia' -13.8333 -171.7667]
 ['San Marino' 43.9333 12.45]
 ['São Tomé' 0.3365 6.7273]
 ['Ar-Riyadh (Riyadh)' 24.6905 46.7096]
 ['Dakar' 14.6937 -17.4441]
 ['Beograd (Belgrade)' 44.8176 20.4633]
 ['Victoria' -4.6167 55.45]
 ['Freetown' 8.484 -13.2299]
 ['Singapore' 1.2897 103.8501]
 ['Philipsburg' 18.026 -63.0458]
 ['Bratislava' 48.1482 17.1067]
 ['Ljubljana' 46.0511 14.5051]
 ['Honiara' -9.4333 159.95]
 ['Muqdisho (Mogadishu)' 2.0416 45.3435]
 ['Cape Town' -33.9258 18.4232]
 ['Juba' 4.8517 31.5825]
 ['Madrid' 40.4165 -3.7026]
 ['Colombo' 6.9319 79.8478]
 ['Al-Quds[East Jerusalem]' 31.7834 35.2339]
 ['Al-Khartum (Khartoum)' 15.5518 32.5324]
 ['Paramaribo' 5.8664 -55.1668]
 ['Mbabane' -26.3167 31.1333]
 ['Stockholm' 59.3326 18.0649]
 ['Bern' 46.9481 7.4474]
 ['Dimashq (Damascus)' 33.5086 36.3084]
 ['Dushanbe' 38.5358 68.7791]
 ['Skopje' 42.0 21.4333]
 ['Krung Thep (Bangkok)' 13.722 100.5252]
 ['Dili' -8.5601 125.5668]
 ['Lomé' 6.1375 1.2123]
 ['Tokelau' -9.38 -171.25]
 ["Nuku'alofa" -21.1394 -175.2032]
 ['Port of Spain' 10.6662 -61.5166]
 ['Tunis' 36.819 10.1658]
 ['Ankara' 39.9199 32.8543]
 ['Ashgabat' 37.95 58.3833]
 ['Cockburn Town' 21.4612 -71.1419]
 ['Funafuti' -8.5189 179.1991]
 ['Kampala' 0.3163 32.5822]
 ['Kyiv (Kiev)' 50.4454 30.5186]
 ['Abu Zaby (Abu Dhabi)' 24.4648 54.3618]
 ['London' 51.5085 -0.1257]
 ['Dodoma' -6.1722 35.7395]
 ['Washington, D.C.' 38.8951 -77.0364]
 ['Charlotte Amalie' 18.3419 -64.9307]
 ['Montevideo' -34.8335 -56.1674]
 ['Tashkent' 41.2647 69.2163]
 ['Port Vila' -17.7338 168.3219]
 ['Caracas' 10.488 -66.8792]
 ['Hà Noi' 21.0245 105.8412]
 ['Matu-Utu' -13.2816 -176.1745]
 ['El Aaiún' 27.1532 -13.2014]
 ["Sana'a'" 15.3531 44.2078]
 ['Lusaka' -15.4134 28.2771]
 ['Harare' -17.8294 31.0539]]
Data Types: object
Riyadh Latitude: <class 'numpy.float64'> Longitude: <class 'numpy.float64'>

TypeError: loop of ufunc does not support argument 0 of type float which has no callable sqrt method

#### Practical Exercise 2

Use NumPy to:

1. Print the names of the countries of the top 10 capital cities closest to the US capital - Washington DC.

2. Create and print a NumPy array containing the coordinates of the top 10 cities.

In [45]:
import pandas as pd
import numpy as np

# Read the CSV file
data = pd.read_csv('/Users/reema/Downloads/country-capital-lat-long-population (1).csv')

# Convert Latitude and Longitude to numeric and drop rows with NaN values
data['Latitude'] = pd.to_numeric(data['Latitude'], errors='coerce')
data['Longitude'] = pd.to_numeric(data['Longitude'], errors='coerce')
data.dropna(subset=['Latitude', 'Longitude'], inplace=True)  # Remove rows with NaN coordinates

# Get Washington D.C.'s coordinates
dc_coords = data.loc[data['Capital City'] == 'Washington, D.C.', ['Latitude', 'Longitude']].values.flatten()

# Ensure we have valid coordinates for Washington, D.C.
if dc_coords.size == 0:
    raise ValueError("Washington, D.C. not found in the dataset.")

# Get coordinates of all capital cities
capitals_coords = data[['Country', 'Capital City', 'Latitude', 'Longitude']].values

# Calculate Euclidean distances to Washington D.C.
distances = np.sqrt((capitals_coords[:, 2] - dc_coords[0]) ** 2 + (capitals_coords[:, 3] - dc_coords[1]) ** 2)

# Get indices of the top 10 closest capital cities
closest_indices = np.argsort(distances)[:10]

# Print the names of the countries and their coordinates
print("Top 10 closest capital cities to Washington D.C.:")
for index in closest_indices:
    country = capitals_coords[index, 0]
    capital = capitals_coords[index, 1]
    coords = capitals_coords[index, 2:4]  # Get latitude and longitude
    print(f"{country} - {capital}: (Latitude: {coords[0]}, Longitude: {coords[1]})")

# Create and print a NumPy array containing the coordinates of the top 10 cities
top_10_coords = capitals_coords[closest_indices, 2:4]  # Extract only Latitude and Longitude
print("\nCoordinates of the top 10 closest capital cities:")
print(top_10_coords)

TypeError: loop of ufunc does not support argument 0 of type float which has no callable sqrt method